#!/bin/sh

pwd_=$PWD
yawm_=$HOME/.yawm
bin_=$yawm_/bin
keys_=$yawm_/keys
panel_=$yawm_/panel

mkdir -p $yawm_
mkdir -p $HOME/bin
mkdir -p $bin_
mkdir -p $keys_
mkdir -p $panel_

unlink $HOME/bin/yawm

cp -v bin/yawm $HOME/bin/
cp -v etc/start-yawm $HOME/bin/
cp -v etc/xinitrc $HOME/.xinitrc-yawm
cp -v etc/yawmrc $HOME/.yawmrc
cp -v etc/autostart $yawm_/

cp -v bin/menu $bin_/
cp -v bin/clock $bin_/
cp -v bin/dock $bin_/
cp -v bin/cpumon $bin_/
cp -v tools/main-menu $panel_/menu

cd $HOME

if [ ! -L .xinitrc ]; then
	mv -v .xinitrc .xinitrc-$(date +%Y%m%d-%H%M%S%s)
fi

ln -sf .xinitrc-yawm .xinitrc

# set defaults

mkdir -p $yawm_/screens/0/tags/0

cd $keys_

if [ ! -f ctrl_alt_delete ]; then
	printf "#!/bin/sh\nexec xscreensaver-command -lock &" > ctrl_alt_delete
	chmod +x ctrl_alt_delete
fi

printf "#!/bin/sh\nexec main-menu &" > mod_m
chmod +x mod_m
