#!/bin/sh

pwd_=$PWD
fwm_=$HOME/.fwm
bin_=$fwm_/bin
keys_=$fwm_/keys
panel_=$fwm_/panel

dirs_="
$fwm_
$HOME/bin
$bin_
$keys_
$panel_
"

for dir in $dirs_; do
	mkdir -p $dir
done

installbin()
{
	for prog in $@; do
		if [ "$prog" = "all:" ]; then
			continue
		fi

		if [ "$prog" = "fwm" ]; then
			unlink $HOME/bin/$prog
			cp -v bin/$prog $HOME/bin/
		else
			unlink $bin_/fwm-$prog
			cp -v bin/fwm-$prog $bin_/
		fi
	done
}

while read line; do
	case $line in
	"all: "*) installbin $line ;;
	esac
done < Makefile

cp -v etc/startfwm $HOME/bin/
cp -v etc/xinitrc $HOME/.xinitrc-fwm
cp -v etc/fwmrc $HOME/.fwmrc
cp -v etc/autostart $fwm_/
cp -v tools/main-menu $panel_/menu

cd $HOME

if [ ! -L .xinitrc ]; then
	mv -v .xinitrc .xinitrc-$(date +%Y%m%d-%H%M%S%s)
fi

ln -sf .xinitrc-fwm .xinitrc

# set defaults

mkdir -p $fwm_/screens/0/tags/0
touch $fwm_/panel/top

cd $keys_

if [ ! -f ctrl_alt_delete ]; then
	printf "#!/bin/sh\nexec xscreensaver-command -lock &" > ctrl_alt_delete
	chmod +x ctrl_alt_delete
fi

printf "#!/bin/sh\nexec xterm &" > mod_t
chmod +x mod_t
printf "#!/bin/sh\nexec main-menu &" > mod_m
chmod +x mod_m
