#!/bin/sh

force_=0
base_=$HOME/.yawm
keys_=$base_/keys
ctl_=$base_/.control$DISPLAY
ifs_=$IFS

help()
{
	local app=$(basename $0)

	printf "$app <options>\nOptions:\n  -f|--force  override existing keys\n"
	exit 0
}

parse() { key_="$1"; pos_="$2"; shift 2; cmd_="$@"; }

# tools: <key>:<position>:<cmd>

cp -v tools/menu-colors $base_/colors

tools_="
mod_e:center:yawm-tagmenu
mod_k:center:yawm-keys
mod_l:center:yawm-clients
mod_m:center:yawm-menu
mod_o:center:yawm-screens
mod_p:center:yawm-apps
mod_r:center:yawm-run
mod_v:center:yawm-clipboard
:center:yawm-suspend
:dock:yawm-clock
::yawm-restart
"

case $1 in
-h|--help) help;;
-f|--force) force_=1;;
esac

mkdir -p $HOME/bin
mkdir -p $keys_

for tool in $tools_; do
	key_=''
	pos_=''
	cmd_=''
	IFS=':'; parse $tool; IFS=$ifs_

	if [ -z "$cmd_" ]; then
		continue
	fi

	cp -v tools/$cmd_ $HOME/bin/
	chmod 0755 $HOME/bin/$cmd_

	if [ -n "$pos_" ]; then
		mkdir -p $base_/$pos_
		touch $base_/$pos_/$cmd_
	fi

	if [ -z "$key_" ]; then
		continue
	fi

	if [ $force_ -eq 0 ] && [ -f $keys_/$key_ ]; then
		printf "key \033[0;32m$key_\033[0m already defined\n"
		printf "run with -f parameter to override\n"
		continue
	fi

	printf "#!/bin/sh\nexec $cmd_ &\n" > $keys_/$key_
	chmod 0755 $keys_/$key_
done

if [ -p $ctl_ ]; then
	echo "reload-keys" > $ctl_
fi
