out = clock
src = clock.c
cflags += $(xftcflags)
ldflags += $(xftldflags) -lxcb -lX11 -lX11-xcb

.PHONY: FORCE clean

$(out): FORCE
	$(cc) -o $(out) $(src) $(cflags) $(ldflags)

include Makefile.common
