out = yawm
src = yawm.c
cflags += $(xftcflags)
ldflags += -lm -lxcb -lxcb-randr -lxcb-util -lxcb-keysyms
ldflags += -lX11 -lX11-xcb $(xftldflags)

.PHONY: FORCE clean

$(out): FORCE
	$(cc) -o $(out) $(src) $(cflags) $(ldflags)

include Makefile.common
