out = menu
src = menu.c
cflags = $(xftcflags)
ldflags = $(xftldflags) -lxcb -lX11 -lX11-xcb -lxcb-keysyms
ldflags += -lxkbcommon -lxkbcommon-x11

.PHONY: FORCE clean

$(out): FORCE
	$(cc) -o $(out) $(src) $(cflags) $(ldflags)

include Makefile.common
