#!/bin/bash

. $base_/head "$1"

list="home:home"
list+="|apps:apps"
list+="|wincfg:wins"
list+="|scrcfg:screens"
list+="|tagcfg:tags"
list+="|netcfg:network"

echo '</head>
<body style="background-color:#ffffff">
<header>
<table style=width:100%;>
<tr>
<td>
<table class=menu>
<tr>'
if [ $# -eq 2 ]; then
	ifs="$IFS"
	IFS='|'
	for item in $list; do
		tag=$(getvar_ ':' $item)
		val=$(getval_ ':' $item)
		if [ "$2" = "$tag" ]; then
			class="selected"
		elif [ "$2" != "$tag" -a "$tag" = "home" ]; then
			class="home"
		else
			class="menu"
		fi
		if [ "$tag" = "home" ]; then
			echo "<td class=menu><label class=icon>
<a class=$class href=cgi?$tag>&#xf015;</a></td></label>"
		else
			echo "<td class=menu>
<a class=$class href=cgi?$tag><b>$val</b></a></td>"
		fi
	done
	IFS="$ifs"
fi
echo '</tr>
</table>
</td>
</tr>
</table>
</header>
<br>'
