#!/bin/bash

. $base_/head "$1"

list="home:home"
list+="|apps:apps"
list+="|wincfg:wins"
list+="|scrcfg:screens"
list+="|tagcfg:tags"
list+="|netcfg:network"

# using table makes it working with browsers with weak CSS support
echo '</head>
<body style="background-color:#ffffff">
<header>
<table style="width:100%;">
<tr>
<td>
<table style="padding:4px;">
<tr>'
if [ $# -eq 2 ]; then
	ifs="$IFS"
	IFS='|'
	for item in $list; do
		tag=$(getvar_ ':' $item)
		val=$(getval_ ':' $item)
		if [ "$2" = "$tag" ]; then
			bg="style=\"color:#fff\";text-decoration:underline;"
		elif [ "$2" != "$tag" -a "$tag" = "home" ]; then
			bg="style=\"color:#304A67\";text-decoration:underline;"
		else
			bg="style=\"color:#111\";text-decoration:none;"
		fi
		if [ "$tag" = "home" ]; then
			echo "<td style=\"padding:8px;\">
<label class=\"icon\">
<a $bg class=\"menu\" href=\"cgi?$tag\">&#xf015;</a></td>
</label>"
		else
			echo "<td style=\"padding:8px;\">
<a $bg class=\"menu\" href=\"cgi?$tag\"><b>$val</b></a></td>"
		fi
	done
	IFS="$ifs"
fi
echo '</tr>
</table>
</td>
</tr>
</table>
</header>
<br>'
