#!/bin/sh

. $base_/menu "network" "netcfg"

getaddr()
{
	ifconfig $1 | while read line; do
		i=$((i + 1))
		if [ $i -eq 1 ]; then
			continue
		fi
		case $line in
		inet*) index_ ' ' 2 "$line"; break;;
		*) echo "0.0.0.0";;
		esac
	done
}

fg="#555"
color="style=color:$fg;"
ip4style="type=text maxlength=15 size=11"
resstyle="type=reset value=&#xf021; title=reset $color"
recstyle="type=submit value=&#xf021; title=reset $color"

pwd=$PWD
cd /sys/class/net/
echo "<table class=legend id=devices>
<tr>
<td class=bgleft>type</td>
<td class=bgleft>name</td>
<td class=bgleft>auto</td>
<td class=bgleft>address</td>
<td class=bgleft>netmask</td>
<td class=bgleft>broadcast</td>
<td class=bgleft></td>
<td class=bgleft></td>
</tr>"
for iface in *; do
	type=0
	read type < $iface/type
	if [ $type -ne 1 ]; then
		continue
	fi
	if [ $((i % 2)) -eq 0 ]; then
		class="class=even"
	else
		class="class=odd"
	fi
	i=$((i + 1))
	$pwd/$base_/getip $iface | while read ip mask bcast hw; do
echo '<tr>'
		if [ -d $iface/wireless ]; then
echo "<form action=cgi>
<input name=cmd type=hidden value=netcfg>
<input name=dev type=hidden value=$iface>
<input name=type type=hidden value=2>
<td $class style=text-align:center;color:$fg; title=wireless>&#xf1eb;</td>
<td $class>$iface</td>
<td $class></td>
<td $class><input $ip4style name=inet value=$ip readonly></td>
<td $class><input $ip4style name=nmask value=$mask readonly></td>
<td $class><input $ip4style name=bcast value=$bcast readonly></td>
<td $class><input $recstyle></td>
<td $class></td>"
		else
echo "<form action=cgi>
<input name=cmd type=hidden value=netcfg>
<input name=dev type=hidden value=$iface>
<input name=type type=hidden value=1>
<td $class style=text-align:center;color:$fg; title=wired>&#xf1e6;</td>
<td $class >$iface</td>
<td $class>
<input type=checkbox name=auto title=automatic configuration>
</td>
<td $class><input $ip4style name=inet value=$ip></td>
<td $class><input $ip4style name=nmask value=$mask></td>
<td $class><input $ip4style name=bcast value=$bcast></td>
<td $class><input $resstyle></td>
<td $class><input type=submit value=&#xf0c7; $color title=apply changes></td>"
		fi
echo '</form>
</tr>'
	done
done
echo '</table>
</body>
</html>'
cd $pwd
