#!/bin/sh

. $base_/menu "network" "netcfg"

getaddr()
{
	ifconfig $1 | while read line; do
		i=$((i + 1))
		if [ $i -eq 1 ]; then
			continue
		fi
		case $line in
		inet*) index_ ' ' 2 "$line"; break;;
		*) echo "0.0.0.0";;
		esac
	done
}

fg="#555"
color="style=\"color:$fg;\""
ip4style="type=\"text\" maxlength=\"15\" size=\"11\""
resstyle="type=\"reset\" value=\"&#xf021;\" title=\"reset\" $color"
recstyle="type=\"submit\" value=\"&#xf021;\" title=\"reset\" $color"

pwd=$PWD
cd /sys/class/net/
echo "<table class=\"legend\" id=\"devices\">
<tr>
<td class=\"bgleft\">&nbsp;type&nbsp;</td>
<td class=\"bgleft\">&nbsp;name&nbsp;</td>
<td class=\"bgleft\">&nbsp;auto&nbsp;</td>
<td class=\"bgleft\">&nbsp;address&nbsp;</td>
<td class=\"bgleft\">&nbsp;netmask&nbsp;</td>
<td class=\"bgleft\">&nbsp;broadcast&nbsp;</td>
<td class=\"bgleft\">&nbsp;</td>
<td class=\"bgleft\">&nbsp;</td>
</tr>"
for iface in *; do
	type=0
	read type < $iface/type
	if [ $type -ne 1 ]; then
		continue
	fi
	$pwd/$base_/getip $iface | while read ip mask bcast hw; do
echo '<tr>'
		if [ -d $iface/wireless ]; then
echo "<form action=\"cgi\">
<input name=\"cmd\" type=\"hidden\" value=\"netcfg\">
<input name=\"dev\" type=\"hidden\" value=\"$iface\">
<input name=\"type\" type=\"hidden\" value=\"2\">
<td style=\"text-align:center;color:$fg;\" title=\"wireless\">&#xf1eb;</td>
<td>&nbsp;$iface&nbsp;</td>
<td></td>
<td><input $ip4style name=\"inet\" value=\"$ip\" readonly></td>
<td><input $ip4style name=\"nmask\" value=\"$mask\" readonly></td>
<td><input $ip4style name=\"bcast\" value=\"$bcast\" readonly></td>
<td><input $recstyle></td>
<td></td>
<td></td>"
		else
echo "<form action=\"cgi\">
<input name=\"cmd\" type=\"hidden\" value=\"netcfg\">
<input name=\"dev\" type=\"hidden\" value=\"$iface\">
<input name=\"type\" type=\"hidden\" value=\"1\">
<td style=\"text-align:center;color:$fg;\" title=\"wired\">&#xf1e6;</td>
<td>&nbsp;$iface&nbsp;</td>
<td><input type=\"checkbox\" name=\"auto\" title=\"automatic configuration\"></td>
<td><input $ip4style name=\"inet\" value=\"$ip\"></td>
<td><input $ip4style name=\"nmask\" value=\"$mask\"></td>
<td><input $ip4style name=\"bcast\" value=\"$bcast\"></td>
<td><input $resstyle></td>
<td><input type=\"submit\" value=\"&#xf0c7;\" $color title=\"apply changes\"></td>"
		fi
echo '</form>
</tr>'
	done
done
echo '</table>
</body>
</html>'
cd $pwd
