#!/bin/bash

. $base_/menu "home" "home"

prstat()
{
	trace_ "ARGS: $@"
	echo "<tr>"
	while [ $# -ne 0 ]; do
		echo "<td>$1</td>"
		shift 1
	done
	echo "</tr>"
}

ip4()
{
	ip4str=''
	ip4str=$((0x$1 >> 24))
	ip4str=$((0x$1 >> 16 & 0xff)).$ip4str
	ip4str=$((0x$1 >> 8 & 0xff)).$ip4str
	ip4str=$((0x$1 & 0xff)).$ip4str
}

route()
{
	echo "<tr>"
	local class=''
	local i=0
	while [ $# -ne 0 ]; do
		str=$1
		if [ "$str" = "Iface" ]; then
			class=" class=bgleft"
		elif [ -z "$class" ]; then
			if [ $i -eq 1 -o $i -eq 2 -o $i -eq 7 ]; then
				ip4 $1
				str=$ip4str
			fi
		fi
		echo "<td$class>$str</td>"
		i=$((i + 1))
		shift 1
	done
	echo "</tr>"
}

echo "<table class=blank>
<tr><td><b>routes</b><br><br></td></tr>
<tr>
<td>
<table class=legend>"
while read line; do
	route $line
done < /proc/net/route
echo "</table>
</td>
</tr>
<tr><td><br><b>connections</b><br><br></td></tr>
<tr>
<td>
<table class=legend>
<tr>
<td class=bgleft>proto</td>
<td class=bgleft>local</td>
<td class=bgleft>remote</td>
<td class=bgleft>state</td>
<td class=bgleft>program</td>
</tr>"
netstat -a -n -p | while read proto rq sq laddr raddr state pid; do
	if [ -z "$pid" ]; then
		pid='-'
	fi
	case "$proto" in
	tcp|udp)
		class=$(alter_ $row)
		row=$((row + 1))
		echo "<tr>
<td $class>$proto</td>
<td $class>$laddr</td>
<td $class>$raddr</td>
<td $class>$state</td>
<td $class>$pid</td>
</tr>"
		;;
	esac
done
echo '</table>
</td>
</tr>
</table>'

. $base_/tail
