#!/bin/sh

. $base_/menu "tags" "tagcfg"

for scr in $(ls -1 ~/.yawm); do
        case "$scr" in
        [0-9])
	echo "<form action=cgi>
<input name=cmd type=hidden value=tagcfg>
<input name=scr type=hidden value=$scr>
<table class=blank style=border-spacing:4px;>
<tr><td class=info>screen $scr</td></tr>"
	for i in $(ls -1 ~/.yawm/$scr/tags/); do
		tag=$(cat ~/.yawm/$scr/tags/$i/.name)
		echo "<tr>
<td>
<div class=input>
<input type=text style=border:none; name=$i value=$tag>
<button class=symbol style=border:none; type=reset value=reset>&#xf0e2;</button>
</div>
</td>
<td>
<div class=checkbox title='mark for deletion'>
<input type=checkbox id=trash$scr$i name=$i.del hidden>
<label for=trash$scr$i>&#xf014;</label>
</div>
</td>
</tr>"
	done
	echo '<tr>
<td>
<button class=symbol type=submit value=new name=tag title="new tag">&#xf067;</button>
<input class=symbol type=submit value=&#xf0c7; title="apply canges">
</td>
</tr>
</table>
</form>'
	;;
	esac
done

. $base_/tail
