#!/bin/sh

. $base_/menu "tags" "tagcfg"

for scr in $(ls -1 ~/.yawm); do
        case "$scr" in
        [0-9])
	echo "<form action=cgi>
<input name=cmd type=hidden value=tagcfg>
<input name=scr type=hidden value=$scr>
<table class=legend id=legend$scr>
<tr><td class=bright>screen $scr</td></tr>
<tr><td>
<table class=tags border=0 id=scr$scr>"
		for i in $(ls -1 ~/.yawm/$scr/tags/); do
			tag=$(cat ~/.yawm/$scr/tags/$i/.name)
			echo "<tr>
<td><input type=text name=$i value=$tag></td>
<td>
<button class=symbol type=reset value=reset>&#xf0e2;</button>
</td>
<td>
<div id=toggle>
<label title='mark for deletion'>
<input type=checkbox name=$i.del hidden><span>&#xf014;</span>
</label>
</div>
</td>
</tr>"
		done
	echo '<tr>
<td>
<button class=symbol type=submit value=new name=tag title="new tag">&#xf067;</button>
</td>
<td><input class=symbol type=submit value=&#xf0c7; title="apply canges"></td>
</tr>
</table>
</td></tr>
</table>
</form>
<br>'
	;;
	esac
done
echo '</body>
</html>'
