#!/bin/sh

. $base_/menu "tags" "tagcfg"

for scr in $(ls -1 ~/.yawm); do
        case "$scr" in
        [0-9])
	echo "<form action=cgi>
<input name=cmd type=hidden value=tagcfg>
<input name=scr type=hidden value=$scr>
<table class=legend id=legend$scr>
<tr><td class=bright>screen $scr</td></tr>
<tr><td>
<table class=tags border=0 id=scr$scr>"
		for i in $(ls -1 ~/.yawm/$scr/tags/); do
			tag=$(cat ~/.yawm/$scr/tags/$i/.name)
			echo "<tr>
<td><input type=text name=$i value=$tag></td>
<td>
<button class=image style=color:#555; type=reset value=reset>&#xf021;</button>
</td>
<td>
<label class=checkbox style='color:#DE5958;border:1px solid #aaa;'>
<input type=checkbox name=$i.del>&#xf014;</label>
</td>
</tr>"
		done
	echo '<tr>
<td><input type=submit value=new name=tag></td>
<td><input type=submit value=apply></td>
</tr>
</table>
</td></tr>
</table>
</form>
<br>'
	;;
	esac
done
echo '</body>
</html>'
