#!/bin/sh

. $base_/menu "wins" "wincfg"

color1="#f8f8f8"
color2="#101010"
image=''
w=24
h=24

echo "<table id=wins>"

wmctrl -l -p | sort |
while read wid desktop pid user name; do
	i=$((i + 1))
	if [ $((i % 2)) -eq 0 ]; then
		style=''
		bgcolor="transparent"
	else
		style="style=background-color:$color1;"
		bgcolor="$color1"
	fi

	if [ $pid -ne 0 ]; then
		while read val; do cmd=$val; done < /proc/$pid/comm
	fi

	icon=$(xprop -id $wid | grep -E "^WM_CLASS.*=" | cut -f2 -d'"')
	case "$icon" in
	*[Tt]erm*) glyph="[&#xf120;";;
	[Cc][Pp][Uu]*|*[Mm]on*) glyph="&#xf1fe;";;
	*[Dd]ict*) glyph="&#xf02d;";;
	[Nn]avigator|[Bb]rowser) glyph="&#xf0ac;";;
	[Cc]hrom*) glyph="&#xf268;";;
	[Ff]irefox) glyph="&#xf269;";;
	*[Cc]lock*) glyph="&#xf017;";;
	*) glyph="&#xf013;";;
	esac
	echo "<tr $style>
<td><a class=symbol style=color:#DE5958; href=cgi?close=$wid>&#xf00d;</a></td>
<td>
<form action=cgi? method=get>
<button class=framed title=show window type=submit name=close value=$wid>
<table class=button>
<tr>
<td><span>$glyph</span>
<td>$name</td>
</tr>
</table>
</button>
</form>
</td>
<td title=command>$cmd</td>
<td><a href=cgi?pidinfo=$pid title=show process details>$pid</a></td>
<td><a href=cgi?wininfo=$wid title=show window details>$wid</a></td>
</tr>"
done
echo '</table>
</body>
</html>'
