#!/bin/bash

cat $dir_/wpacli.html

#<input class=symbol type=submit title='re-scan wireless networks' value=&#xf1eb;&nbsp;&nbsp;&#xf021;>

wpa_cli scan $iface 1>&2
sleep 2
echo "<tr><td><br></td></tr>
<tr>
<td>
<form action=cgi>
<input name=cmd type=hidden value=netcfg>
<input name=dev type=hidden value=$iface>
<input name=type type=hidden value=2>
<button class=symbol type=submit title='re-scan wireless networks'>
&#xf1eb;&nbsp;&nbsp;&#xf021;
</button>
</form>
</td>
</tr>
<tr><td><br></td></tr>
<tr>
<td>
<table class=blank style=width:100%;>
<tr>
<td class=info>network</td>
<td class=info>signal</td>
<td class=info>&nbsp;frequency</td>
<td class=info>hotspot</td>
</tr>
<tr><td></td></tr>"
row=0
title=''
wpa_cli scan_results | while read bssid freq sig flg ssid; do
	trace_ "$bssid | $freq | $sig | $flg | $ssid"
	case "$bssid" in
	Selected|OK|bssid) continue;;
	esac
	if [ $freq -lt 5000 ]; then
		frq="2.4GHz"
	else
		frq="5GHz"
	fi
	if [ "$flg" = "[ESS]" ]; then
		lock="&#xf09c;" # open
	else
		lock="&#xf023;"
	fi
	class=$(alter_ $row)
	row=$((row + 1))
	lvl="&nbsp;"
	if [ $sig -gt -50 ]; then
		clr="#111"
		# last &#9633 is for aesthetic reason
		lvl="&#9632;&#9632;&#9632;&#9632;&#9633;&nbsp;$sig"
		sig="excellent"
	elif [ $sig -le -50 -a $sig -ge -60 ]; then
		clr="#555"
		lvl="&#9632;&#9632;&#9632;&#9633;&#9633;&nbsp;$sig"
		sig="good"
	elif [ $sig -lt -60 -a $sig -ge -70 ]; then
		clr="#777"
		lvl="&#9632;&#9632;&#9633;&#9633;&#9633;&nbsp;$sig"
		sig="fair"
	else
		clr="#aaa"
		lvl="&#9632;&#9633;&#9633;&#9633;&#9633;&nbsp;$sig"
		sig="weak"
	fi
	astyle="style=text-decoration:none;"
	echo "<tr>
<td $class>
<div>
<a class=hide id=hide$row href=#hide$row $astyle>$lock &#xf0da; $ssid</a>
<a class=show id=show$row href=#show$row $astyle>$lock &#xf0d7; $ssid</a>
<div class=details style=margin:4px;>
<form name=$row action=cgi? method=post>
<input name=post.wpa type=hidden>
<input name=dev value=$iface type=hidden>
<span class=symbol>&nbsp;&#xf084;&nbsp;</span>
<input class=text type=text name=username value=$ssid hidden>
<input class=text type=password name=key title=key>
<input class=symbol type=submit value=&#xf090; title=connect>
</form>
</div>
</div>
</td>
<td $class title=$sig style=color:$clr;>$lvl</td>
<td $class title=$freq>&nbsp;$frq</td>
<td $class>&nbsp;$bssid</td>
</tr>"
done
echo '</table>
</td>
</tr>'
