#!/bin/bash

wpa_cli scan $iface 1>&2
sleep 2
echo "<form action=cgi>
<input name=cmd type=hidden value=netcfg>
<input name=dev type=hidden value=$iface>
<input name=type type=hidden value=2>
<br>
<b>
<button class=symbol type=submit title='re-scan wireless networks'>
&#xf1eb;&nbsp;&nbsp;&#xf021;
</button>
</b>
</form>
<br>
<table class=legend id=wlan>
<tr>
<td class=bgleft></td>
<td class=bgleft>network</td>
<td class=bgleft>signal</td>
<td class=bgleft></td>
<td class=bgleft>&nbsp;frequency</td>
<td class=bgleft>hotspot</td>"
row=0
title=''
wpa_cli scan_results | while read bssid freq sig flg ssid; do
	trace_ "$bssid | $freq | $sig | $flg | $ssid"
	echo "<tr>"
	case "$bssid" in
	Selected|OK|bssid) continue;;
	esac
	if [ $freq -lt 5000 ]; then
		frq="2.4GHz"
	else
		frq="5GHz"
	fi
	if [ "$flg" = "[ESS]" ]; then
		glyph="&#xf09c;" # open
	else
		glyph="&#xf023;"
	fi
	class=$(alter_ $row)
	split=$(alter_ $row "split")
	row=$((row + 1))
	lvl="&nbsp;"
	if [ $sig -gt -50 ]; then
		clr="#111"
		# last &#9633 is for aesthetic reason
		lvl="&#9632;&#9632;&#9632;&#9632;&#9633;&nbsp;$sig"
		sig="excellent"
	elif [ $sig -le -50 -a $sig -ge -60 ]; then
		clr="#555"
		lvl="&#9632;&#9632;&#9632;&#9633;&#9633;&nbsp;$sig"
		sig="good"
	elif [ $sig -lt -60 -a $sig -ge -70 ]; then
		clr="#777"
		lvl="&#9632;&#9632;&#9633;&#9633;&#9633;&nbsp;$sig"
		sig="fair"
	else
		clr="#aaa"
		lvl="&#9632;&#9633;&#9633;&#9633;&#9633;&nbsp;$sig"
		sig="weak"
	fi
	astyle="style=text-decoration:none;"
	echo "<td $class><span class=symbol>$glyph</span></td>
<td $class>
<div>
<a class=hide id=hide$row href=#hide$row $astyle>&#xf0da; $ssid</a>
<a class=show id=show$row href=#show$row $astyle>&#xf0d7; $ssid</a>
<div class=details style=margin:4px;>
<form name=$row action=cgi? method=post>
<input name=post.wpa type=hidden>
<input name=dev value=$iface type=hidden>
<span class=symbol>&nbsp;&#xf084;&nbsp;</span>
<input class=text type=text name=username value=$ssid hidden>
<input class=text type=password name=key>
<input class=symbol type=submit value=&#xf090; title=connect>
</form>
</div>
</div>
</td>
<td $class title=$sig style=color:$clr;font-family:Monospace>$lvl</td>
<td $split></td>
<td $class title=$freq>&nbsp;$frq</td>
<td $class>&nbsp;$bssid</td>
</tr>"
done
echo '</table>'
