#!/bin/bash

iface=$(getval_ '=' $1)
net=$(getval_ '=' $2)
key=$(getval_ '=' $3)
dir=config/wpa
cfg=$dir/${net}.cfg
err=$dir_/${net}.err
nok=1

failed()
{
	local msg="<span class=symbol style=color:red><strong>$net</strong>: connection failed</span>"
	local astyle="style=text-decoration:none;"

	echo "<div>
<a class=hide id=hidewpacli href=#hidewpacli $astyle>&#xf0da; $msg</a>
<a class=show id=showwpacli href=#showwpacli $astyle>&#xf0d7; $msg</a>
<div class=details style=margin:4px;>
<pre>"
	cat $cfg
	cat $err
	echo '</pre>
</div>
</div><br>'
}

waitcon()
{
	while read line; do
		if [ "$line" = "wpa_state=COMPLETED" ]; then
			nok=0
		fi
	done < $err
}

mkdir -p $dir
echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=wheel" > $cfg
chmod 0600 $cfg
if wpa_passphrase $net $key 2>$err 1>>$cfg; then
	if sudo /etc/wpa_supplicant/wpa_reconfigure $PWD/$cfg >$err 2>&1; then
		for i in 1 2 3 4 5 6 7 8; do
			if ! wpa_cli status >$err 2>&1; then
				break
			else
				waitcon
				if [ $nok -eq 0 ]; then
					break
				fi
			fi
			sleep 1
		done
	fi
fi

if [ $nok -ne 0 ]; then
	status=1
	failed
fi
