#!/bin/sh

spawn()
{
	exec $@ &
	sleep 0.3 # FIXME: have to delay or wm will miss window creation event
}

wlan=0
lan=0

for iface in /sys/class/net/*; do
	read type < $iface/type

	if [ -d $iface/wireless ]; then
		if [ $wlan -eq 0 ]; then
			spawn wlan-dock
			wlan=1
		fi
	elif [ "$type" = "1" ]; then
		if [ $lan -eq 0 ]; then
			spawn lan-dock
			lan=1
		fi
	elif [ $lan -eq 1 -a $wlan -eq 1 ]; then
		break
	fi
done

for power in /sys/class/power_supply/*; do
	read type < $power/type
	case $type in
	*attery*) spawn bat-dock;;
	*ains*) spawn ac-dock;;
	esac
done

for sound in /dev/snd/*; do
	case $sound in
	*dev*snd*pcm*) spawn mixer-dock; break;;
	esac
done

spawn usb-dock
spawn display-dock
spawn cpu-dock
spawn clock-dock
