#!/bin/sh

export FWM_HOME=$HOME/.fwm
export FWM_LOG=$HOME/fwm${DISPLAY}.log

case $PATH in
*$FWM_HOME/bin*) ;;
*) export PATH=$PATH:$FWM_HOME/bin;;
esac

if [ -f $HOME/bin/xkbmap ]; then
	$HOME/bin/xkbmap
fi

fwm
restart-menu

if [ $? -eq 0 ]; then
	fwm-cleanup
	exit 0
fi
