#!/bin/sh

export FWM_HOME=$HOME/.fwm
export FWM_LOG=$HOME/fwm${DISPLAY}.log
export FWM_FONT=/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
export FWM_ICONS=$HOME/.fonts/fontawesome/fontawesome-webfont.ttf
export FWM_FONT_SIZE=7

if [ -f $FWM_HOME/screenrc ]; then
	# provides screen specific variables in order to maintain readable
	# font size for hight resolution displays, e.g. for 4K displays:
	#
	# export GDK_SCALE=2
	# export FWM_HDPI=266
	# export FWM_VDPI=266
	#
	. $FWM_HOME/screenrc
fi

case $PATH in
*$FWM_HOME/bin*)
	;;
*) export PATH=$PATH:$FWM_HOME/bin
	;;
esac

if [ -f $HOME/bin/xkbmap ]; then
	$HOME/bin/xkbmap
fi

fwm
fwm-cleanup
