#!/bin/sh

xset -b
setxkbmap -model pc105 -variant nodeadkeys -option grp:alt_shift_toggle \
	-layout "fi(nodeadkeys),ru"
xsetroot -solid black -cursor_name left_ptr
xscreensaver -no-splash &

while :; do
	. ~/.yawmrc
	yawm
	yawm-restart

	if [ $? -eq 0 ]; then
		break
	fi
done
