#!/bin/sh

etc_=/etc/wpa_supplicant
var_=/var/run/wpa_supplicant
sys_=/sys/class/net
dev_=''
ifs_=$IFS
err_=0

help()
{
	echo "Usage: $(basename $0) <ssid>"
}

getdev()
{
	while [ $# -gt 1 ]; do
		shift 1
	done
	dev_=$1
}

error()
{
	while read line; do
		case $line in
		*"error"*|*"Error"*|*"ERROR"*|*"fail"*|*"Fail"*|*"FAIL"*)
			echo "$line"
			return 1
			;;
		esac
	done
	return 0
}

cleanup()
{
	ifconfig $dev_ down
	killall dhclient
	killall -9 dhclient
}

restart()
{
	if [ -f /etc/init.d/wpa_supplicant ]; then
		/etc/init.d/wpa_supplicant restart
	else
		killall wpa_supplicant 2>/dev/null
		killall -9 wpa_supplicant 2>/dev/null
		wpa_supplicant -s -B -i$dev_ -c /etc/wpa_supplicant/current.conf
	fi
	err_=$?
}

connect()
{
	ifconfing $dev_ up
	dhclient $dev_
	err_=$?
}

if [ $# -eq 0 ]; then
	help
	exit 0
fi

for dir in $sys_/*; do
	if [ -d $dir/wireless ]; then
		IFS='/'; getdev $dir; IFS=$ifs_
		break
	fi
done

if [ -z "$dev_" ]; then
	echo "wireless interface not found"
	exit 1
fi

cd $etc_
echo "ctrl_interface=DIR=$var_ GROUP=root" > current.conf
while read line; do
	echo "$line" >> current.conf
done < configs/"$@"
ln -sf current.conf wpa_supplicant.conf
cleanup
restart 2>&1 | error

if [ $err_ -ne 0 ]; then
	# reset config
	echo "ctrl_interface=DIR=$var_ GROUP=root" > current.conf
	restart 2>&1 | error
	exit 1
fi

connect 2>&1 | error

if [ $err_ -eq 0 ]; then
	echo "ok $dev_"
fi
