#!/bin/sh

etc_=/etc/wpa_supplicant
var_=/var/run/wpa_supplicant
sys_=/sys/class/net
dev_=''
ifs_=$IFS
err_=0
dhcpc_=''
dhcpa_=''

help()
{
	echo "Usage: $(basename $0) <ssid>"
}

getdev()
{
	while [ $# -gt 1 ]; do
		shift 1
	done
	dev_=$1
}

error()
{
	while read line; do
		case $line in
		*"error"*|*"Error"*|*"ERROR"*|*"fail"*|*"Fail"*|*"FAIL"*)
			echo "$line"
			return 1
			;;
		esac
	done
	return 0
}

cleanup()
{
	ifconfig $dev_ down
	killall $dhcpc_
	killall -9 $dhcpc_
}

restart()
{
	# we do not want to use startu up script even if it is present
	if [ -x /etc/init.d/wpa_supplicant ]; then
		/etc/init.d/wpa_supplicant stop 2>/dev/null
	fi

	killall wpa_supplicant 2>/dev/null
	killall -9 wpa_supplicant 2>/dev/null
	ifconfig $dev_ up
	wpa_supplicant -B -i $dev_ -c /etc/wpa_supplicant/current.conf
	err_=$?
}

connect()
{
	ifconfing $dev_ up
	$dhcpc_ $dhcpa_ $dev_
	err_=$?
}

if which dhclient >/dev/null; then
	dhcpc_=dhclient
elif which udhcpc >/dev/null; then
	dhcpc_=udhcpc
	dhcpa_='-i'
else
	echo "(ee) no DHCP client found"
	exit 1
fi

if [ $# -eq 0 ]; then
	help
	exit 0
fi

for dir in $sys_/*; do
	if [ -d $dir/wireless ]; then
		IFS='/'; getdev $dir; IFS=$ifs_
		break
	fi
done

if [ -z "$dev_" ]; then
	echo "wireless interface not found"
	exit 1
fi

cd $etc_
echo "ctrl_interface=DIR=$var_ GROUP=root" > current.conf
while read line; do
	echo "$line" >> current.conf
done < configs/"$@"
ln -sf current.conf wpa_supplicant.conf
cleanup
restart 2>&1 | error

if [ $err_ -ne 0 ]; then
	# reset config
	echo "ctrl_interface=DIR=$var_ GROUP=root" > current.conf
	restart 2>&1 | error
	exit 1
fi

connect 2>&1 | error

if [ $err_ -eq 0 ]; then
	echo "ok $dev_"
fi
