#!/bin/sh

. $FWM_HOME/lib/menu-utils

normbg
normfg

icon_=""
name_=ac-dock
comm_=/dev/null
dimfg_=$(printf "0x%x" $((normbg_ + 0x202020)))
online_=''

update()
{
	read online < /sys/class/power_supply/AC/online

	if [ "$online_" != "$online" ]; then
		if [ $online -eq 1 ]; then
			updatedock $name_ $icon_ $normfg_
		else
			updatedock $name_ $icon_ $dimfg_
		fi
	fi

	online_=$online
}

initmon $name_ $comm_
startdock $name_ $icon_ $normbg_ $normfg_ $comm_
sleep 0.5 # give window some time to settle
update

while :; do
	fwm-netlink | while read msg; do
		case $msg in
		change@*power_supply*AC*) online_=1; update;;
		change@*power_supply*BAT*) online_=0; update;;
		esac
	done
done
