#!/bin/sh

. $YAWM_HOME/lib/menu-utils

normbg
normfg

icon_=""
name_=ac-dock
comm_=/dev/null
dimfg_=$(printf "0x%x" $((normbg_ + 0x202020)))
online_=0

update()
{
	read online < /sys/class/power_supply/AC/online

	if [ $online_ != $online ]; then
		if [ $online -eq 1 ]; then
			updatedock $name_ $icon_ $normfg_
		else
			updatedock $name_ $icon_ $dimfg_
		fi
	fi

	online_=$online
}

initmon $name_ $comm_
startdock $name_ $icon_ $normbg_ $normfg_ $comm_
update

while :; do
	if netlink; then
		update
	else
		sleep 1 # relax
	fi
done
