#!/bin/sh

. $YAWM_HOME/lib/menu-utils

ifs_=$IFS
tmp_=$YAWM_HOME/tmp
out_=$tmp_/menu

printf "" > $out_

while read line; do
	split() { var=$1; val=$2; }
	IFS='='; split $line
	printf "$var\t$val\n" >> $out_
done < /sys/class/power_supply/BAT0/uevent

IFS=$ifs_

showinfo $out_
