#!/bin/sh

. $YAWM_HOME/lib/menu-utils

icon_=""
name_=bat-dock
comm_=bat-info
capacity_=0

normbg
normfg

initmon $name_ $comm_

while :; do
	read capacity < /sys/class/power_supply/BAT0/capacity

	if [ "$capacity_" != "$capacity" ]; then
		if [ $capacity -gt 100 ]; then
			capacity=100
			icon_=""  # full
		elif [ $capacity -ge 75 -a $capacity -le 100 ]; then
			icon_=""  # high
		elif [ $capacity -ge 25 -a $capacity -lt 75 ]; then
			icon_="" # normal
		else
			icon_="" # low
		fi

		startdock $name_ "$icon_:$capacity" $normbg_ $normfg_ $comm_
	fi

	capacity_=$capacity
	sleep 60
done
