#!/bin/sh

. $FWM_HOME/lib/menu-utils

normbg
normfg

icon_=""
name_=bat-dock
comm_=bat-info
capacity_=0

update()
{
	local rc=1

	read capacity < /sys/class/power_supply/BAT0/capacity

	if [ "$capacity_" != "$capacity" ]; then
		if [ $capacity -gt 100 ]; then
			capacity=100
			icon_=""  # full
		elif [ $capacity -ge 75 -a $capacity -le 100 ]; then
			icon_=""  # high
		elif [ $capacity -ge 25 -a $capacity -lt 75 ]; then
			icon_="" # normal
		else
			icon_="" # low
		fi
		rc=0
	fi

	capacity_=$capacity
	return $rc
}

read capacity < /sys/class/power_supply/BAT0/capacity
initmon $name_ $comm_
update
startdock $name_ $icon_ $normbg_ $normfg_ $comm_ "-t $capacity_%"

while :; do
	sleep 60

	if update; then
		updatedock $name_ $icon_ $normfg_ $capacity_%%
	fi
done
