#!/bin/sh

. $FWM_HOME/lib/menu-utils

name_=clock-dock
comm_=clock-menu

stoptool fwm-clock $name_
normbg
normfg

exec fwm-clock -n $name_ -bg $normbg_ -fg $normfg_ -f "%Y-%m-%d/%W %a %H:%M"\
	       -c $comm_ &
