#!/bin/sh

. $FWM_HOME/lib/menu-utils

name_=cpu-dock

stoptool fwm-cpumon $name_
normbg
normfg

monitor()
{
	exec fwm-cpumon -n $name_ -bg $normbg_ -fg $normfg_ -bw 1 -f 60 -i 60\
			-c $1 &
}

i=0

while read cpu info; do
	cpu_="cpu$i"
	case $cpu in
	$cpu_) monitor $i; i=$((i + 1));;
	esac
done < /proc/stat
