#!/bin/sh

. $FWM_HOME/lib/menu-utils

script_=$FWM_RANDR_SCRIPT

disconnect_monitor()
{
	xrandr | while read name status prim rest; do
		case $name in
		[0-9]*|Screen|eDP*) continue;;
		esac

		echo "xrandr --output \"$name\" --off" >> $script_
	done
	echo reinit-outputs > $ctl_
}

connect_monitor()
{
	local pos='--left-of'
	local auto=0

	case $1 in
	right) pos='--right-of';;
	auto) auto=1;;
	esac

	xrandr | while read name status role rest; do
		case $role in
		primary) primary=$name; continue;;
		esac

		case $name in
		[0-9]*|Screen|eDP*) continue;;
		esac

		case $status in
		*disconnected*) continue;;
		esac

		if [ $auto -eq 1 ]; then
			pos="--left-of"
			auto=$((auto + 1))
		elif [ $auto -eq 2 ]; then
			pos="--right-of"
			auto=$((auto + 1))
		fi

		echo "xrandr --output \"$name\" --auto $pos \"$primary\"" >> $script_

		if [ $auto -gt 2 ]; then
			break
		fi
	done
	echo reinit-outputs > $ctl_
}

echo -n > $script_
chmod 0755 $script_

ctl_=$FWM_HOME/.control$DISPLAY
tmp_=$FWM_HOME/tmp
out_=$tmp_/menu

#printf "\a\t\n" > $out_
printf "\a\t\n" > $out_
printf "\a\tbrightness\n" >> $out_
printf "\a\tleft\n" >> $out_
printf "\a\tright\n" >> $out_
printf "\a\tauto\n" >> $out_
printf "\a\tdisconnect\n" >> $out_

startmenu -b -d $out_ | while read icon item; do
	case $item in
	"brightness"*) exec brightness-menu &;;
	"left"*) connect_monitor left;;
	"right"*) connect_monitor right;;
	"auto"*) connect_monitor auto;;
	"disconnect"*) disconnect_monitor;;
	esac
done
