#!/bin/sh

. $FWM_HOME/lib/menu-utils

ctl_=$FWM_HOME/.control$DISPLAY
tmp_=$FWM_HOME/tmp
out_=$tmp_/menu
edid_=$tmp_/edid
props_=$tmp_/xrandr-props.txt
connected_=$tmp_/randr-connected.txt
pri_=eDP-1

hexdump_edid()
{
	hexdump -v -e '16/1 "%02x"' -e '"\n"' $1 2>/dev/null
}

find_primary_output()
{
	while read name status role info; do
		case $role in
		primary)
			pri_=$name
			break
			;;
		esac
	done < $props_
}

#
# Only interested in first 256 bytes of EDID.
#
extract_sysfs_edid()
{
	local i=0
	local sysfs=/sys/class/drm

	rm -f $edid_/sysfs/edids/*.txt
	rm -f $edid_/sysfs/strings/*.txt

	for card in $sysfs/card*; do
		hexdump_edid $card/edid > $edid_/sysfs/edids/$i.txt

		strings $card/edid 2>/dev/null |\
			tr -d '\n' > $edid_/sysfs/strings/$i.txt

		i=$((i + 1))
	done
}

match_output()
{
	local found=1
	local strings_file=''
	local output_name=''

	for randr_edid in $edid_/outputs/*; do
		for sysfs_edid in $edid_/sysfs/edids/*.txt; do 
			diff $randr_edid $sysfs_edid >/dev/null 2>&1
			found=$?

			if [ $found -eq 0 ]; then
				output_name=$(basename $randr_edid)
				strings_file=$edid_/sysfs/strings/$(basename $sysfs_edid)
				break
			fi
		done
	done

	if [ $found -eq 0 ]; then
		printf "\a\t$output_name\t$(cat $strings_file 2>/dev/null)\n" >> $out_
		printf "\a\t$output_name\tnon-desktop\n" >> $out_
		printf "\a\t$output_name\tdisconnect\n" >> $out_
	fi
}

find_connected_displays()
{
	local output=''
	local found_output=0
	local found_edid=0
	local line=0

	xrandr |\
	grep -E "^[A-Za-z0-9].*[[:blank:]]connected" |\
	cut -f1 -d' ' |\
	grep -v "eDP" > $connected_

	while read name; do
		line=$(grep -n $name $props_ | cut -f1 -d':')
		tail -n +$line $props_ | while read name status rest; do
			case $status in
			disconnected)
				break
				;;
			connected)
				output=$name
				found_output=1
				echo -n > $edid_/outputs/${output}
				continue
				;;
			esac

			if [ $found_output -eq 0 ]; then
				continue
			fi

			case $name in
			EDID:)
				found_edid=1
				continue
				;;
			esac

			if [ $found_edid -eq 0 ]; then
				continue
			fi

			case $name in
			*[g-zA-Z-:+]*)
				continue
				;;
			[0-9abcdef]*)
				echo $name >> $edid_/outputs/${output}
				;;
			esac
		done

		found_output=0
		found_edid=0
	done < $connected_
}

connect_hmd()
{
	touch $FWM_HOME/panel/skip/$1
	mkdir -p $FWM_HOME/screens/hmd
	echo $1 > $FWM_HOME/screens/hmd/name
	xrandr --output $1 --prop --set non-desktop 0 --auto --above $pri_
}

connect_nondesktop()
{
	xrandr --output $1 --set non-desktop 1
}

disconnect_hmd()
{
	xrandr --output $1 --off
}

handle_hmd()
{
	case $2 in
	non-desktop) connect_nondesktop $1;;
	disconnect) disconnect_hmd $1;;
	*) connect_hmd $1;;
	esac
}

mkdir -p $edid_/sysfs/edids $edid_/sysfs/strings $edid_/outputs

xrandr --prop > $props_

find_connected_displays
find_primary_output
extract_sysfs_edid

#printf "\a\t\n" > $out_
printf "\a\t\t\n" > $out_

match_output

startmenu -b -d $out_ | while read icon item info; do
	case $item in
	[A-Z]*) handle_hmd $item $info;;
	esac
done
