#!/bin/sh

if ! pidof xscreensaver >/dev/null 2>&1; then
	xscreensaver -no-splash &
fi

for i in 0 1 2 3 4 5 6 7 8 9; do
	if pidof xscreensaver >/dev/null 2>&1; then
		break
	fi
	sleep 1
done

xscreensaver-command -lock
