#!/bin/sh

. $FWM_HOME/lib/menu-utils

ctl_=$FWM_HOME/.control$DISPLAY
tmp_=$FWM_HOME/tmp
out_=$tmp_/menu

#printf "\a\t\n" > $out_
printf "\a\t\n" > $out_
printf "\a\trun...\n" >> $out_
printf "\a\tterminal\n" >> $out_
printf "\a\tfirefox\n" >> $out_
printf "\a\tchrome\n" >> $out_
#printf "\a\tlinks\n" >> $out_
printf "\a\tfiles\n" >> $out_
printf "\a\tclipboard\n" >> $out_
printf "\a\tapplications\n" >> $out_
printf "\a\tlist\n" >> $out_
printf "\a\tshortcuts\n" >> $out_
printf "\a\tgrid\n" >> $out_
printf "\a\ttag editor\n" >> $out_
#   fa-moon-o [&#xf186;]
#   fa-hotel (alias) [&#xf236;]
#   fa-pause [&#xf04c;]
printf "\a\twifi\n" >> $out_
printf "\a\tsound\n" >> $out_
printf "\a\tdisplay\n" >> $out_
printf "\a\tsuspend\n" >> $out_
printf "\a\texit\n" >> $out_

exit_fwm()
{
	xrandr | while read name status role rest; do
		case $status in
		*disconnected*)
			continue
			;;
		esac
		xrandr --output "$name" --brightness 0
	done
	stopcmd fwm
}

startmenu -b -d $out_ | while read icon item; do
	case $item in
	"run..."*) exec run-menu &;;
	"terminal"*) exec xterm &;;
	"firefox"*) exec firefox &;;
	"chrome"*) exec chromium-browser &;;
	"files"*) exec spacefm &;;
	"clipboard"*) exec clip-menu &;;
	"applications"*) exec apps-menu &;;
	"list"*) exec clients-menu &;;
	"shortcuts"*) exec keys-menu &;;
	"grid"*) printf "make-grid" > $ctl_;;
	"tag editor"*) tag-menu &;;
	"wifi"*) wlan-menu &;;
	"sound"*) mixer-menu &;;
	"display"*) display-menu &;;
	"suspend"*) suspend-menu &;;
	"exit"*) exit_fwm;;
	esac
	break
done
