#!/bin/sh

. $YAWM_HOME/lib/menu-utils

tmp_=$YAWM_HOME/tmp
out_=$tmp_/restart

mkdir -p $tmp_

if [ ! -f $out_ ]; then
	printf "Restart window manager\t\a \n" > $out_
	printf "Leave desktop session\t\a \n" >> $out_
fi

startmenu -d $out_ | while read info icon; do
	case $info in
	Restart*) return 1;;
	Leave*) return 0;;
	esac
done
