#!/bin/sh

. $YAWM_HOME/lib/menu-utils

ifs_=$IFS
tmp_=$YAWM_HOME/tmp
out_=$tmp_/bin

mkdir -p $tmp_

#printf "\a\t\n" > $out_
printf "\a\t\n" > $out_

IFS=':'

for dir in $PATH; do
	ls -1 $dir | while read line; do
		printf "$line\t$dir\n" >> $out_
	done
done

IFS=$ifs_

startmenu -b -d -a $out_ | while read cmd path extra; do
	if [ -z "$extra" ]; then
		exec $cmd &
	else
		IFS=' '
		exec $extra &
	fi

	break
done
