#!/bin/sh

. $FWM_HOME/lib/menu-utils

ctl_=$FWM_HOME/.control$DISPLAY
scr_=$FWM_HOME/tmp/screens

echo list-screens > $ctl_

startmenu -b -d $scr_ | while read scr line; do
	echo "focus-screen $scr" > $ctl_
	exit 0
done
