#!/bin/sh

width=30
height=9

tmp=$HOME/.yawm/tmp
run=$tmp/scrlist
res=$tmp/scrlist.fifo

mkdir -p $tmp
mkfifo $res

echo "DIALOGRC=\$HOME/.yawm/dialogrc" > $run
echo "export DIALOGRC" >> $run

items=0
for scr in $HOME/.yawm/screens/*; do
	items=$((items + 1))
done

printf "dialog --nook --no-cancel --menu ' ' $height $width $items" >> $run
i=0
for scr in $HOME/.yawm/screens/*; do
	printf " $i screen$i" >> $run
	i=$((i + 1))
done
printf " 2>$res\n" >> $run
chmod +x $run
cat $run

export ST_CURSOR_TYPE=8 # hide cursor
exec $HOME/bin/st -t scrlist -g ${width}x$height -e sh -c $run &
read res < $res
if [ -n "$res" ]; then
	xsetroot -name "focus-screen $res"
	echo $res
fi
