#!/bin/sh

. $FWM_HOME/lib/menu-utils

tmp_=$FWM_HOME/tmp
out_=$tmp_/suspend
log_=$tmp_/suspend.log

mkdir -p $tmp_

suspend()
{
	if ! pidof xscreensaver >/dev/null 2>&1; then
		xscreensaver -no-splash &
	fi

	for i in 0 1 2 3 4 5 6 7 8 9; do
		if pidof xscreensaver >/dev/null 2>&1; then
			break
		fi
		sleep 1
	done

#	xdotool key Alt+Control+F1
	xscreensaver-command --lock
#	sleep 2
	jedi pm-suspend >$log_ 2>&1
}

if [ ! -f $out_ ]; then
	printf "Suspend system\t\a\n" > $out_
	printf "Cancel\t\n" >> $out_
fi

startmenu -d $out_ | while read info icon; do
	case $info in
	Suspend*) suspend; return 1;;
	esac
done
