#!/bin/sh

. $FWM_HOME/lib/menu-utils

tmp_=$FWM_HOME/tmp
out_=$tmp_/suspend
log_=$tmp_/suspend.log

mkdir -p $tmp_

suspend()
{
	pidof xscreensaver

	if [ $? -ne 0 ]; then
		exec xscreensaver -no-splash &
	fi

#	xdotool key Alt+Control+F1
	xscreensaver-command --lock
#	sleep 2
	sudo pm-suspend >$log_ 2>&1
}

if [ ! -f $out_ ]; then
	printf "Suspend system\t\a\n" > $out_
	printf "Cancel\t\n" >> $out_
fi

startmenu -d $out_ | while read info icon; do
	case $info in
	Suspend*) suspend; return 1;;
	esac
done
