#!/bin/sh

. $FWM_HOME/lib/menu-utils

ctl_=$FWM_HOME/.control$DISPLAY
tmp_=$FWM_HOME/tmp
seq_=$tmp_/.seq
out_=$tmp_/tagmenu
maxtags_=255
scr_=0
tag_=-1
name_=''
wcnt_=0

mkdir -p $tmp_

help()
{
	printf "Usage: $1 new-tag-name\n" > $out_
	showinfo $out_
}

create()
{
	local name=$1
	local tag=0
	local path=''

	while :; do
		path=$FWM_HOME/screens/$scr_/tags/$tag

		if [ ! -d $path ]; then
			mkdir -p $path

			if [ -z "$name" ]; then
				name=$tag
			fi

			printf "$name" > $path/.name
			echo "refresh-panel $scr_" > $ctl_
			return
		fi

		tag=$((tag + 1))

		if [ $tag -ge $maxtags_ ]; then
			return
		fi
	done
}

delete()
{
	if [ $wcnt_ -ne 0 ]; then
		return
	fi

	rm -fr $FWM_HOME/screens/$scr_/tags/$tag_
	echo "refresh-panel $scr_" > $ctl_
}

rename()
{
	if [ $# -eq 0 ]; then
		help r
		return 1
	fi

	local path=$FWM_HOME/screens/$scr_/tags/$tag_

	if [ ! -d $path ]; then
		return
	fi

	printf "$1" > $path/.name
	echo "refresh-panel $scr_" > $ctl_
}

topmenu()
{
	read prevseq < $seq_
	echo list-tags > $ctl_

	count=0
	while :; do
		read curseq < $seq_
		if [ $prevseq -ne $curseq -o $count -gt 5 ]; then
			break
		fi
		count=$((count + 1))
		sleep 0.1
	done

	while read scr tag name geo wcnt cur win; do
		if [ "$cur" = '1' ]; then
			scr_=$scr
			tag_=$tag
			name_=$name
			wcnt_=$wcnt
			break
		fi
	done < $tmp_/tags

	if [ -z "$tag_" ]; then
		exit 1
	fi

	if [ $tag_ -lt 0 ]; then
		exit 1
	fi

	#printf "\a\t\n" > $out_
	printf "\a\t\n" > $out_
	printf "\a\tcreate <name>\n" >> $out_

	if [ $wcnt_ -eq 0 ]; then
		printf "\a\tdelete [$name_]\n" >> $out_
	fi

	printf "\a\trename <newname>\n" >> $out_

	startmenu -b -a -d $out_ |
	while read icon item param cmd arg; do
		case $item in
		"create"*) create $arg;;
		"delete"*) delete;;
		"rename"*) rename $arg;;
		esac
	done
}

rc=1

while [ $rc -gt 0 ]; do
	topmenu
	rc=$?

	if [ $rc -eq 0 ]; then
		break
	fi
done
