#!/bin/sh

. $YAWM_HOME/lib/menu-utils

icon_=""
name_=wlan-dock
comm_=wlan-menu
level_=0

ifstatus()
{
	ifconfig $1 | while read line; do
		case $line in
		*inet*addr:[0-9]*) return 1;;
		esac
	done
}

status()
{
	iwconfig 2>/dev/null | while read line; do
		case $line in
		*IEEE*ESSID:off/any) return 0;;
		*IEEE*ESSID*) ifstatus $line; return $?;;
		esac
	done
}

restart() { startdock $name_ $icon_ $normbg_ $1 $comm_; }

initmon $name_ $comm_

status
oldstat=$?
newstat=0

normbg
normfg
dimfg_=$(printf "0x%x" $((normbg_ + 0x202020)))

if [ $oldstat -eq 1 ]; then
	restart $normfg_
elif [ $oldstat -eq 0 ]; then
	restart $dimfg_
fi

while :; do
	status
	newstat=$?

	if [ $newstat -eq $oldstat ]; then
		sleep 2
		continue
	elif [ $newstat -eq 1 ]; then
		restart $normfg_
	elif [ $newstat -eq 0 ]; then
		restart $dimfg_
	fi

	oldstat=$newstat
	sleep 2
done
