#!/bin/sh

. $FWM_HOME/lib/menu-utils

normbg
normfg
selbg
selfg

menu_="-0 $normfg_ -1 $normbg_ -2 $selfg_ -3 $selbg_"
info_="-0 $normfg_ -1 $normbg_ -2 $normfg_ -3 $normbg_"

mainmenu_=$0
etc_=/etc/wpa_supplicant
tmp_=/tmp/$USER/wlan
out_=$tmp_/menu
inf_=$tmp_/info

mkdir -p $tmp_

run() { $@ >/dev/null 2>&1; }

setup()
{
	printf "\a\t$1\n" > $out_

	startmenu -b -a -d $out_ |
	while read icon ssid key; do
		if [ -z "$key" ]; then
			break
		fi

		echo "$1 $key" | sudo iwadd | while read error; do
			err=1

			case $error in
			"ok") err=0;;
			*) printf "\a\t$error\n" > $out_;;
			esac

			if [ $err -ne 0 ]; then
				showinfo -d $out_
			fi

			break
		done
	done

	$mainmenu_
}

add()
{
	printf "\a\tscanning...\n" > $out_
	showinfo -d $out_ &

	run sudo iwlist wlan0 scan
	run sudo wpa_cli scan

	printf "\a\t\n" > $out_

	sudo wpa_cli scan_results | while read bssid freq sig flags ssid; do
		case $bssid in
		OK|Selected|bssid) continue;;
		esac

		if [ $sig -gt -50 ]; then
			lvl="    " # excellent
		elif [ $sig -le -50 -a $sig -ge -60 ]; then
			lvl="    " # good
		elif [ $sig -lt -60 -a $sig -ge -70 ]; then
			lvl="    " # fair
		else
			lvl="    " # weak
		fi

		if [ -z "$ssid" ]; then
			ssid="??"
		fi

		printf "\a$lvl\t$ssid\n" >> $out_
	done

	startmenu -b -a -d $out_ |
	while read bar0 bar1 bar2 bar4 bar5 ssid input; do
		if [ -n "$ssid" ]; then
			setup $ssid
			$mainmenu_
		fi

		break
	done
}

connected()
{
	printf "\a\tnot connected\n" > $out_

	ifconfig $2 | while read inet addr rest; do
		case $addr in
		"addr:"[0-9]*)
			printf "\a\tconnected to $1 $addr\n" > $out_
			break
			;;
		esac
	done

	if ! ping -c 1 $pinghost_ >/dev/null 2>&1; then
		printf "\a\tno internet connection\n" >> $out_
	fi

	showinfo -d $out_
}

connect()
{
	printf "\a\tconnecting to $ssid ...\n" > $inf_
	showinfo -d $inf_ &

	sudo iwup $1 | while read status message; do
		if [ -z "$message" ]; then
			printf "\a\t$1: unknown status\n" > $out_
			showinfo -d $out_
			break
		fi

		err=1

		case $status in
		"ok") err=0;;
		*) printf "\a\t$status $message\n" > $out_;;
		esac

		if [ $err -ne 0 ]; then
			showinfo -d $out_
			$mainmenu_
		else
			connected $1 $message
		fi

		break
	done
}

manage()
{
	local cur=$etc_/current.conf
	local ico=''

	if [ "$1" = "del" ]; then
		ico=""
	else
		ico=""
	fi

	printf "\a\t\n" > $out_

	ls -1 $etc_/configs/ | while read config; do
		printf "\a$ico\t$config\n" >> $out_
	done

	startmenu -b -d $out_ |
	while read icon ssid; do
		if [ -z "$ssid" ]; then
			break
		elif [ "$1" = "del" ]; then
			sudo iwdel $ssid
		else
			connect $ssid
		fi

		break
	done
}

sig_=-71
getsignal() { sig_=$1; }

level()
{
	local ifs=$IFS

	IFS=' '; getsignal $3; IFS=$ifs
	if [ $sig_ -gt -50 ]; then
		lvl="||||||||||||---"
	elif [ $sig_ -le -50 -a $sig -ge -60 ]; then
		lvl="|||||||||------"
	elif [ $sig_ -lt -60 -a $sig -ge -70 ]; then
		lvl="||||||---------"
	else
		lvl="|||------------"
	fi

	printf "$lvl|\n" >> $out_
}

devstat()
{
	local ifs=$IFS

	printf "" > $out_

	iwconfig $1 | while read dev line; do
		case $dev in
		*ink*) printf "\t\t  $line " >> $out_
		       IFS='='; level $line; IFS=$ifs;;
		$1) printf "\t$dev\t  $line\n" >> $out_;;
		*) printf "\t\t  $line\n" >> $out_;;
		esac
	done

	ifconfig $1 | while read dev line; do
		case $dev in
		$1) printf "\t$dev\t  $line\n" >> $out_;;
		*) printf "\t\t  $line\n" >> $out_;;
		esac
	done

	showinfo $out_
}

status()
{
	iwconfig 2>/dev/null | while read line; do
		case $line in
		*IEEE*ESSID*) devstat $line;;
		esac
	done
}

disconnect()
{
	while read iface dest rest; do
		case $dest in
		"00000000")
			if [ -d /sys/class/net/$iface/wireless ]; then
				sudo ifdown $iface
			fi
			;;
		esac
	done < /proc/net/route
}

printf "\a\t\n" > $out_
printf "\a\tconnect\n" >> $out_
printf "\a\tadd\n" >> $out_
printf "\a\tforget\n" >> $out_
printf "\a\tstatus\n" >> $out_
printf "\a\tdisconnect\n" >> $out_

startmenu -b -a -d $out_ |
while read icon item cmd arg; do
	case $item in
	"connect") manage;;
	"disconnect") disconnect;;
	"add") add;;
	"forget") manage del;;
	"status") status;;
	esac
done
