#!/bin/sh

. ~/.yawm/colors/menu-colors

signal() { stopdock; exit 0; }
cleanup() { kill -9 $1 >/dev/null 2>&1; }

stopdock()
{
	ps -opid,args | while read pid cmd; do
		case $cmd in
		*dock*-n*yawm-batmon*) kill $pid >/dev/null 2>&1; break;;
		esac
	done
}

restart()
{
	stopdock
	dock -n yawm-batmon -i $icon -bg $norbg -fg $norfg -c yawm-batinfo &
}

pid_=$$

ps -opid,args | while read line; do
	case $line in
	$pid_*) continue;;
	*yawm-batmon*bin*sh*) cleanup $line;;
	esac
done

trap signal SIGINT SIGTERM SIGKILL

level_=0

while :; do
	read level < /sys/class/power_supply/BAT0/capacity_level
	case $level in
	Full) icon="";;
	Low) icon="";;
	Normal) icon="";;
	High) icon="";;
	*) icon="";;
	esac

	if [ "$level_" != "$level" ]; then
		restart $icon
	fi

	level_=$level
	sleep 60
done
