#!/bin/sh

. ~/.yawm/colors/menu-colors

ctl_=$HOME/.yawm/.control$DISPLAY
tmp_=$HOME/.yawm/tmp
out_=$tmp_/menu

#printf "\a\t\n" > $out_
printf "\a  \t\n" > $out_
printf "\a  \trun...\n" >> $out_
printf "\a  \tterminal\n" >> $out_
printf "\a  \tfirefox\n" >> $out_
printf "\a  \tchrome\n" >> $out_
#printf "\a  \tlinks\n" >> $out_
printf "\a  \tfiles\n" >> $out_
printf "\a  \tclipboard\n" >> $out_
printf "\a  \tapplications\n" >> $out_
printf "\a  \twindows\n" >> $out_
printf "\a  \tshortcuts\n" >> $out_
printf "\a  \tgrid\n" >> $out_
printf "\a  \ttag editor\n" >> $out_
printf "\a  \texit\n" >> $out_

menu -n yawm-menu -b $colors_ -c 30 -d $out_ |
while read icon item; do
	echo "'$item'"
	case $item in
	"run..."*) exec yawm-run &;;
	"terminal"*) exec xterm &;;
	"firefox"*) exec firefox;;
	"chrome"*) exec chromium-browser;;
	"files"*) exec pcmanfm;;
	"clipboard"*) exec yawm-clipboard;;
	"applications"*) exec yawm-apps &;;
	"windows"*) exec yawm-clients &;;
	"shortcuts"*) exec yawm-keys &;;
	"grid"*) printf "make-grid" > $ctl_;;
	"tag editor"*) yawm-tagmenu &;;
	"exit"*) killall yawm;;
	esac
done
