#!/bin/sh

read bg_ < $HOME/.yawm/colors/normal-bg
read fg_ < $HOME/.yawm/colors/normal-fg

monitor()
{
	sleep 0.1
	exec cpumon -bg $bg_ -fg $fg_ -bw 1 -f 60 -i 60 -c $1 &
}

killall -9 cpumon

i=0

while read cpu info; do
	cpu_="cpu$i"
	case $cpu in
	$cpu_) monitor $i; i=$((i + 1));;
	esac
done < /proc/stat
