#!/bin/sh

. ~/.yawm/colors/menu-colors

ps -opid,args | while read pid cmd; do
	case $cmd in
	*dock*-c*yawm-volume*) kill $pid >/dev/null 2>&1; break;;
	esac
done

case $1 in
mute)
	read fg < ~/.yawm/colors/normal-bg
	fg=$(printf "0x%x" $((fg + 0x202020)))
	;;
low)
	read fg < ~/.yawm/colors/normal-bg
	fg=$(printf "0x%x" $((fg + 0x404040)))
	;;
max) read fg < ~/.yawm/colors/notice-bg;;
*) read fg < ~/.yawm/colors/normal-fg;;
esac

dock -n yawm-mixer -i "" -bg $norbg -fg $fg -c yawm-volume &
