#!/bin/sh

ctl_=$HOME/.yawm/.control
cli_=$HOME/.yawm/clients

while read var val; do
	case "$var" in
	seq*) seq=$val;;
	esac
done < $cli_

echo list-clients > $ctl_

found=0
count=0
while :; do
	while read var val; do
		case "$var" in
		seq*)
			if [ "$seq" != "$val" ]; then
				found=1
				break
			fi
			;;
		esac
	done < $cli_
	if [ $found -eq 1 -o $count -gt 500 ]; then
		break
	fi
	count=$((count + 1))
	sleep 0.1
done

menu -n yawm-clients -c 80 -r 24 -d -s 5 $cli_ |
while read scr tag win info; do
	echo "focus-window $win" > $ctl_
	exit 0
done
