#!/bin/sh

ctl_=$HOME/.yawm/.control
cli_=$HOME/.yawm/tmp/clients
seq_=$HOME/.yawm/tmp/.seq

while read var val; do
	case "$var" in
	seq*) seq=$val;;
	esac
done < $cli_

read prevseq < $seq_
echo list-clients > $ctl_

count=0
while :; do
	read curseq < $seq_
	if [ $prevseq -ne $curseq -o $count -gt 5 ]; then
		break
	fi
	count=$((count + 1))
	sleep 0.1
done

menu -n yawm-clients -b -s 5 -d $cli_ |
while read scr tag win info; do
	echo "focus-window $win" > $ctl_
	exit 0
done
