#!/bin/sh

ifs_=$IFS
tmp_=$HOME/.yawm/tmp
out_=$tmp_/bin

mkdir -p $tmp_

printf "" > $out_
IFS=':'
for dir in $PATH; do
	ls -1 $dir | while read line; do
		printf "$line\t$dir\n" >> $out_
	done
done

IFS='	'
menu -n yawm-run -d -a $out_ | while read cmd path extra; do
	if [ -z "$extra" ]; then
		exec $cmd &
	else
		IFS=' '
		exec $extra &
	fi

	break
done
