#!/bin/sh

width=30
height=7
items=0
list=''

cli=$HOME/.yawm/clients
ctl=$HOME/.yawm/.control
tmp=$HOME/.yawm/tmp
run=$tmp/screens
res=$tmp/screens.fifo

present()
{
	for item in $list; do
		if [ "$item" = "$1" ]; then
			return 0
		fi
	done
	return 1
}

while read var val; do
	case "$var" in
	seq*) seq=$val;;
	esac
done < $cli

echo list-clients > $ctl

found=0
count=0
while :; do
	while read var val; do
		case "$var" in
		seq*)
			if [ "$seq" != "$val" ]; then
				found=1
				break
			fi
			;;
		esac
	done < $cli
	if [ $found -eq 1 -o $count -gt 5000 ]; then
		break
	fi
	count=$((count + 1))
done

mkdir -p $tmp
mkfifo $res 2>/dev/null

echo "DIALOGRC=\$HOME/.yawm/dialogrc" > $run
echo "export DIALOGRC" >> $run

while read scr tag win status pid name; do
	case "$scr" in
	seq*) continue;;
	esac
	if present $scr; then
		continue
	fi
	eval "list=\"\$list \$scr screen\$scr\""
	items=$((items + 1))
done < $cli

height=$((height + items))
printf "dialog --nook --no-cancel --menu ' ' " >> $run
printf "$height $width $items" >> $run
printf "$list 2>$res\n" >> $run
chmod +x $run
cat $run

export ST_CURSOR_TYPE=8 # hide cursor
exec $HOME/bin/st -t scrlist -g ${width}x$height -e sh -c $run &
read res < $res
if [ -n "$res" ]; then
	echo "focus-screen $res" > $ctl
fi
