#!/bin/sh

. ~/.yawm/colors/menu-colors

ifs_=$IFS
tmp_=$HOME/.yawm/tmp/volume
out_=$tmp_/menu
inf_=$tmp_/info
max_=0
cur_=0
cid_=''

mkdir -p $tmp_

setmax() { max_=$1; }
setcur() { cur_=$2; }
volume() { amixer cset "$2" "$1,$1" >/dev/null; }

default()
{
	local cid=$1

	amixer cget $cid | while read line; do
		setmax0() { max=$1; }
		setmax() { IFS=','; setmax0 $6; }
		case $line in
		*values*min*max*) IFS='='; setmax $line;;
		esac

		if [ -n "$max" ]; then
			volume "$max" "$cid"
			return
		fi
	done
}

# max out pcm and speaker and read master info

amixer controls | while read cid; do
	case $cid in
	*PCM*Playback*Volume*) default "$cid" ;;
	*Speaker*Playback*Volume*) default "$cid";;
	*Master*Playback*Volume*) amixer cget "$cid" > $inf_;;
	esac
done

# find out master playback

while read line; do
	case $line in
	numid*Master*Playback*Volume*) cid_=$line; break;;
	esac
done < $inf_

# find out max and cur values

IFS='='
while read v1 v2 v3 v4 v5 v6; do
	case $v1 in
	*:*values=[0-9]*) IFS='='; setcur $v1;;
	esac

	case $v6 in
	[0-9]*,step*) IFS=','; setmax $v6;;
	esac
done < $inf_

printf "\a\t$cur_\n" > $out_
printf "\a\tmute\n" >> $out_
printf "\a\tlow\n" >> $out_
printf "\a\tmed\n" >> $out_
printf "\a\tmax\n" >> $out_

# prompt user

IFS=$ifs_
menu -n yawm-menu -b $colors_ -a -d $out_ |
while read icon item arg; do
	case $icon in
	"") volume "$item" "$cid_"; yawm-mixer; exit 0;;
	esac

	case $item in
	mute) volume 0 "$cid_"; yawm-mixer mute;;
	low) volume "$((max_ / 3))" "$cid_"; yawm-mixer low;;
	med) volume "$((max_ / 2))" "$cid_"; yawm-mixer med;;
	max) volume "$max_" "$cid_"; yawm-mixer max;;
	*) volume "$arg" "$cid_"; yawm-mixer;;
	esac
done
